# Generated by Django 5.0.3 on 2024-06-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_item_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user_name',
            new_name='user',
        ),
    ]
